name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add this step to verify our location
      - name: Debug directory
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          echo "Building the Docker image..."
          # Using . since we're already in the correct directory after checkout
          docker build -t apod-api:latest .
          echo "Docker image built successfully!"

      - name: Tag Docker Image
        run: |
          echo "Tagging the Docker image..."
          docker tag apod-api:latest ${{ secrets.DOCKER_USERNAME }}/apod-api:latest
          echo "Docker image tagged successfully!"

      - name: Push Docker Image
        run: |
          echo "Pushing the Docker image to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/apod-api:latest
          echo "Docker image pushed successfully!"