name: Build and Push Docker Image

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub UI
  push:
    branches:
      - master  # Triggers on push to the 'master' branch
  pull_request:
    branches:
      - master  # Triggers on pull request to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image in the apod-api directory
      - name: Build Docker Image
        run: |
          echo "Building the Docker image..."
          docker build . -t apod-api:latest
        working-directory: apod-api  # Specify the directory directly

      # Step 5: Tag the image with your Docker Hub username
      - name: Tag Docker Image
        run: |
          echo "Tagging the Docker image..."
          docker tag apod-api:latest ${{ secrets.DOCKER_USERNAME }}/apod-api:latest

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          echo "Pushing the Docker image to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/apod-api:latest